SELECT A.AID_YEAR, A.EMPLID, A.PRIMARY_EFC, A.DESCRSHORT, B.PREF_FIRST_NAME, C.AWARD_PERIOD, C.FEDERAL_ID, C.Y_AWD_OFFR_FALL, C.Y_AWD_OFFR_WINT, C.Y_AWD_OFFR_FW_TTL, D.FEDERAL_ID, D.Y_AWD_OFFR_FALL, D.Y_AWD_OFFR_WINT, D.Y_AWD_OFFR_FW_TTL, E.FEDERAL_ID, E.Y_AWD_OFFR_FALL, E.Y_AWD_OFFR_WINT, E.Y_AWD_OFFR_FW_TTL, F.FA_SOURCE, F.Y_AWD_OFFR_FALL, F.Y_AWD_OFFR_WINT, F.Y_AWD_OFFR_FW_TTL, G.FIN_AID_TYPE, G.Y_AWD_OFFR_FALL, G.Y_AWD_OFFR_WINT, G.Y_AWD_OFFR_FW_TTL, I.FED_YEAR_COA, I.FED_TOTAL_AID, I.FED_UNMET_COA, J.Y_BGT_AMNT_CATG, J.Y_BGT_AMNT_FALL, J.Y_BGT_AMNT_WINT, J.Y_BGT_AMNT_FW_TTL, K.Y_BGT_AMNT_CATG, K.Y_BGT_AMNT_FALL, K.Y_BGT_AMNT_WINT, K.Y_BGT_AMNT_FW_TTL, L.Y_BGT_AMNT_CATG, L.Y_BGT_AMNT_FALL, L.Y_BGT_AMNT_WINT, L.Y_BGT_AMNT_FW_TTL, M.Y_BGT_AMNT_CATG, M.Y_BGT_AMNT_FALL, M.Y_BGT_AMNT_WINT, M.Y_BGT_AMNT_FW_TTL, N.Y_BGT_AMNT_CATG, N.Y_BGT_AMNT_FALL, N.Y_BGT_AMNT_WINT, N.Y_BGT_AMNT_FW_TTL, P.FA_SOURCE, P.Y_AWD_OFFR_FALL, P.Y_AWD_OFFR_WINT, P.Y_AWD_OFFR_FW_TTL, Q.Y_BGT_AMNT_FALL, Q.Y_BGT_AMNT_WINT, Q.Y_BGT_AMNT_FW_TTL, R.Y_AWD_OFFR_TYPE, R.Y_AWD_OFFR_FALL, R.Y_AWD_OFFR_WINT, R.Y_AWD_OFFR_FW_TTL, S.Y_AWD_OFFR_TYPE, S.Y_AWD_OFFR_FALL, S.Y_AWD_OFFR_WINT, S.Y_AWD_OFFR_FW_TTL, T.Y_AWD_OFFR_TYPE, SUM( T.Y_AWD_OFFR_FALL), SUM( T.Y_AWD_OFFR_WINT), SUM( T.Y_AWD_OFFR_FW_TTL) 
  FROM (((((((((((((((PS_Y_DASH_ISIR_VW A LEFT OUTER JOIN  PS_Y_DASH_AWRD_VW C ON  A.AID_YEAR = C.AID_YEAR AND A.EMPLID = C.EMPLID AND C.FEDERAL_ID = 'PELL' AND C.AWARD_PERIOD = 'A' ) LEFT OUTER JOIN  PS_Y_DASH_AWRD_VW D ON  A.AID_YEAR = D.AID_YEAR AND A.EMPLID = D.EMPLID AND D.FEDERAL_ID = 'STFS' AND D.AWARD_PERIOD = 'A' ) LEFT OUTER JOIN  PS_Y_DASH_AWRD_VW E ON  A.AID_YEAR = E.AID_YEAR AND A.EMPLID = E.EMPLID AND E.FEDERAL_ID = 'STFU' AND E.AWARD_PERIOD = 'A' ) LEFT OUTER JOIN  PS_Y_DASH_AWRD_VW F ON  A.AID_YEAR = F.AID_YEAR AND A.EMPLID = F.EMPLID AND F.FA_SOURCE = 'S' AND F.FIN_AID_TYPE = 'G' AND F.AWARD_PERIOD = 'A' ) LEFT OUTER JOIN  PS_Y_DASH_AWRD_VW G ON  A.AID_YEAR = G.AID_YEAR AND A.EMPLID = G.EMPLID AND G.FIN_AID_TYPE = 'S' AND G.FA_SOURCE = 'I' AND G.AWARD_PERIOD = 'A' ) LEFT OUTER JOIN  PS_Y_DASH_COA_VW J ON  A.AID_YEAR = J.AID_YEAR AND A.EMPLID = J.EMPLID AND J.AWARD_PERIOD = 'A' AND J.Y_BGT_AMNT_CATG = 'TUIT' ) LEFT OUTER JOIN  PS_Y_DASH_COA_VW K ON  A.AID_YEAR = K.AID_YEAR AND A.EMPLID = K.EMPLID AND K.Y_BGT_AMNT_CATG = 'BOOK' AND K.AWARD_PERIOD = 'A' ) LEFT OUTER JOIN  PS_Y_DASH_COA_VW L ON  A.AID_YEAR = L.AID_YEAR AND A.EMPLID = L.EMPLID AND L.Y_BGT_AMNT_CATG = 'TRAN' AND L.AWARD_PERIOD = 'A' ) LEFT OUTER JOIN  PS_Y_DASH_COA_VW M ON  A.AID_YEAR = M.AID_YEAR AND A.EMPLID = M.EMPLID AND M.Y_BGT_AMNT_CATG = 'R&B' AND M.AWARD_PERIOD = 'A' ) LEFT OUTER JOIN  PS_Y_DASH_COA_VW N ON  A.AID_YEAR = N.AID_YEAR AND A.EMPLID = N.EMPLID AND N.Y_BGT_AMNT_CATG = 'OTHR' AND N.AWARD_PERIOD = 'A' ) LEFT OUTER JOIN  PS_Y_DASH_AWRD_VW P ON  A.AID_YEAR = P.AID_YEAR AND A.EMPLID = P.EMPLID AND P.FIN_AID_TYPE = 'L' AND P.FA_SOURCE = 'P' AND P.AWARD_PERIOD = 'A' ) LEFT OUTER JOIN  PS_Y_DASH_COA_T_VW Q ON  A.AID_YEAR = Q.AID_YEAR AND A.EMPLID = Q.EMPLID AND Q.AWARD_PERIOD = 'A' ) LEFT OUTER JOIN  PS_Y_DASH_AWRDT_VW R ON  A.AID_YEAR = R.AID_YEAR AND A.EMPLID = R.EMPLID AND R.AWARD_PERIOD = 'A' AND R.Y_AWD_OFFR_TYPE = 'GS' ) LEFT OUTER JOIN  PS_Y_DASH_AWRDT_VW S ON  A.AID_YEAR = S.AID_YEAR AND A.EMPLID = S.EMPLID AND S.AWARD_PERIOD = 'A' AND S.Y_AWD_OFFR_TYPE = 'LN' ) LEFT OUTER JOIN  PS_Y_DASH_AWRD_VW T ON  A.AID_YEAR = T.AID_YEAR AND A.EMPLID = T.EMPLID AND (( T.FIN_AID_TYPE IN ('V','A')) OR ( T.FIN_AID_TYPE = 'S' AND T.FA_SOURCE <> 'I') OR ( T.FA_SOURCE = 'S' AND T.FIN_AID_TYPE = 'G')) ), PS_PERSON_NAME B, PS_STDNT_AWD_PER I 
  WHERE ( A.AID_YEAR = '2020' 
     AND A.EMPLID = B.EMPLID 
     AND EXISTS (SELECT 'X' 
  FROM PS_STDNT_AWARDS H, PS_ITEM_TYPE_FA O 
  WHERE H.EMPLID = A.EMPLID 
     AND H.AID_YEAR = A.AID_YEAR 
     AND H.OFFER_AMOUNT > 0 
     AND H.FIN_AID_TYPE IN ('G','L') 
     AND H.AID_YEAR = O.AID_YEAR 
     AND H.ITEM_TYPE = O.ITEM_TYPE 
     AND O.SETID = H.SETID 
     AND O.EFFDT = 
        (SELECT MAX(O_ED.EFFDT) FROM PS_ITEM_TYPE_FA O_ED 
        WHERE O.SETID = O_ED.SETID 
          AND O.ITEM_TYPE = O_ED.ITEM_TYPE 
          AND O.AID_YEAR = O_ED.AID_YEAR 
          AND O_ED.EFFDT <= SYSDATE) 
     AND O.FA_SOURCE = 'F' 
     AND (( O.FIN_AID_TYPE = 'G' 
     AND O.FEDERAL_ID = 'PELL') 
     OR ( O.FIN_AID_TYPE = 'L' 
     AND O.FEDERAL_ID IN ('STFS','STFU'))) 
     AND ( H.ACAD_CAREER = 'UGRD' 
     OR ( H.ACAD_CAREER = 'GRAD' 
     AND EXISTS (SELECT 'X' 
  FROM PS_STDNT_FA_TERM U 
  WHERE U.EFFDT = 
        (SELECT MAX(U_ED.EFFDT) FROM PS_STDNT_FA_TERM U_ED 
        WHERE U.EMPLID = U_ED.EMPLID 
          AND U.INSTITUTION = U_ED.INSTITUTION 
          AND U.STRM = U_ED.STRM 
          AND U_ED.EFFDT <= SYSDATE) 
    AND U.EFFSEQ = 
        (SELECT MAX(U_ES.EFFSEQ) FROM PS_STDNT_FA_TERM U_ES 
        WHERE U.EMPLID = U_ES.EMPLID 
          AND U.INSTITUTION = U_ES.INSTITUTION 
          AND U.STRM = U_ES.STRM 
          AND U.EFFDT = U_ES.EFFDT) 
     AND U.EMPLID = H.EMPLID 
     AND U.INSTITUTION = H.INSTITUTION 
     AND U.AID_YEAR = H.AID_YEAR 
     AND U.ACAD_LEVEL_BOT = '50')))) 
     AND A.AID_YEAR = I.AID_YEAR 
     AND A.EMPLID = I.EMPLID 
     AND I.AWARD_PERIOD = 'A' 
     AND NOT EXISTS (SELECT 'X' 
  FROM PS_COMMUNICATION V, PS_VAR_DATA_FINA W 
  WHERE V.COMMON_ID = A.EMPLID 
     AND V.COMMON_ID = W.COMMON_ID 
     AND W.VAR_DATA_SEQ = V.VAR_DATA_SEQ 
     AND W.AID_YEAR = A.AID_YEAR 
     AND V.ADMIN_FUNCTION = 'FINA' 
     AND V.COMM_CATEGORY = 'FAMSG1' 
     AND V.COMM_CONTEXT = 'FANU19' 
     AND V.SCC_LETTER_CD = 'FN1')) 
  GROUP BY  A.AID_YEAR,  A.EMPLID,  A.PRIMARY_EFC,  A.DESCRSHORT,  B.PREF_FIRST_NAME,  C.AWARD_PERIOD,  C.FEDERAL_ID,  C.Y_AWD_OFFR_FALL,  C.Y_AWD_OFFR_WINT,  C.Y_AWD_OFFR_FW_TTL,  D.FEDERAL_ID,  D.Y_AWD_OFFR_FALL,  D.Y_AWD_OFFR_WINT,  D.Y_AWD_OFFR_FW_TTL,  E.FEDERAL_ID,  E.Y_AWD_OFFR_FALL,  E.Y_AWD_OFFR_WINT,  E.Y_AWD_OFFR_FW_TTL,  F.FA_SOURCE,  F.Y_AWD_OFFR_FALL,  F.Y_AWD_OFFR_WINT,  F.Y_AWD_OFFR_FW_TTL,  G.FIN_AID_TYPE,  G.Y_AWD_OFFR_FALL,  G.Y_AWD_OFFR_WINT,  G.Y_AWD_OFFR_FW_TTL,  I.FED_YEAR_COA,  I.FED_TOTAL_AID,  I.FED_UNMET_COA,  J.Y_BGT_AMNT_CATG,  J.Y_BGT_AMNT_FALL,  J.Y_BGT_AMNT_WINT,  J.Y_BGT_AMNT_FW_TTL,  K.Y_BGT_AMNT_CATG,  K.Y_BGT_AMNT_FALL,  K.Y_BGT_AMNT_WINT,  K.Y_BGT_AMNT_FW_TTL,  L.Y_BGT_AMNT_CATG,  L.Y_BGT_AMNT_FALL,  L.Y_BGT_AMNT_WINT,  L.Y_BGT_AMNT_FW_TTL,  M.Y_BGT_AMNT_CATG,  M.Y_BGT_AMNT_FALL,  M.Y_BGT_AMNT_WINT,  M.Y_BGT_AMNT_FW_TTL,  N.Y_BGT_AMNT_CATG,  N.Y_BGT_AMNT_FALL,  N.Y_BGT_AMNT_WINT,  N.Y_BGT_AMNT_FW_TTL,  P.FA_SOURCE,  P.Y_AWD_OFFR_FALL,  P.Y_AWD_OFFR_WINT,  P.Y_AWD_OFFR_FW_TTL,  Q.Y_BGT_AMNT_FALL,  Q.Y_BGT_AMNT_WINT,  Q.Y_BGT_AMNT_FW_TTL,  R.Y_AWD_OFFR_TYPE,  R.Y_AWD_OFFR_FALL,  R.Y_AWD_OFFR_WINT,  R.Y_AWD_OFFR_FW_TTL,  S.Y_AWD_OFFR_TYPE,  S.Y_AWD_OFFR_FALL,  S.Y_AWD_OFFR_WINT,  S.Y_AWD_OFFR_FW_TTL,  T.Y_AWD_OFFR_TYPE